// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.21.2
// source: face.proto

package pbface

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// FaceServiceClient is the client API for FaceService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type FaceServiceClient interface {
	FaceFunc(ctx context.Context, in *FaceRequest, opts ...grpc.CallOption) (*FaceResponse, error)
}

type faceServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewFaceServiceClient(cc grpc.ClientConnInterface) FaceServiceClient {
	return &faceServiceClient{cc}
}

func (c *faceServiceClient) FaceFunc(ctx context.Context, in *FaceRequest, opts ...grpc.CallOption) (*FaceResponse, error) {
	out := new(FaceResponse)
	err := c.cc.Invoke(ctx, "/FaceService/FaceFunc", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// FaceServiceServer is the server API for FaceService service.
// All implementations must embed UnimplementedFaceServiceServer
// for forward compatibility
type FaceServiceServer interface {
	FaceFunc(context.Context, *FaceRequest) (*FaceResponse, error)
	mustEmbedUnimplementedFaceServiceServer()
}

// UnimplementedFaceServiceServer must be embedded to have forward compatible implementations.
type UnimplementedFaceServiceServer struct {
}

func (UnimplementedFaceServiceServer) FaceFunc(context.Context, *FaceRequest) (*FaceResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method FaceFunc not implemented")
}
func (UnimplementedFaceServiceServer) mustEmbedUnimplementedFaceServiceServer() {}

// UnsafeFaceServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to FaceServiceServer will
// result in compilation errors.
type UnsafeFaceServiceServer interface {
	mustEmbedUnimplementedFaceServiceServer()
}

func RegisterFaceServiceServer(s grpc.ServiceRegistrar, srv FaceServiceServer) {
	s.RegisterService(&FaceService_ServiceDesc, srv)
}

func _FaceService_FaceFunc_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FaceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FaceServiceServer).FaceFunc(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/FaceService/FaceFunc",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FaceServiceServer).FaceFunc(ctx, req.(*FaceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// FaceService_ServiceDesc is the grpc.ServiceDesc for FaceService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var FaceService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "FaceService",
	HandlerType: (*FaceServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "FaceFunc",
			Handler:    _FaceService_FaceFunc_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "face.proto",
}

// ClusterServiceClient is the client API for ClusterService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ClusterServiceClient interface {
	ClusterFunc(ctx context.Context, in *ClusterRequest, opts ...grpc.CallOption) (*ClusterResponse, error)
}

type clusterServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewClusterServiceClient(cc grpc.ClientConnInterface) ClusterServiceClient {
	return &clusterServiceClient{cc}
}

func (c *clusterServiceClient) ClusterFunc(ctx context.Context, in *ClusterRequest, opts ...grpc.CallOption) (*ClusterResponse, error) {
	out := new(ClusterResponse)
	err := c.cc.Invoke(ctx, "/ClusterService/ClusterFunc", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ClusterServiceServer is the server API for ClusterService service.
// All implementations must embed UnimplementedClusterServiceServer
// for forward compatibility
type ClusterServiceServer interface {
	ClusterFunc(context.Context, *ClusterRequest) (*ClusterResponse, error)
	mustEmbedUnimplementedClusterServiceServer()
}

// UnimplementedClusterServiceServer must be embedded to have forward compatible implementations.
type UnimplementedClusterServiceServer struct {
}

func (UnimplementedClusterServiceServer) ClusterFunc(context.Context, *ClusterRequest) (*ClusterResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ClusterFunc not implemented")
}
func (UnimplementedClusterServiceServer) mustEmbedUnimplementedClusterServiceServer() {}

// UnsafeClusterServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ClusterServiceServer will
// result in compilation errors.
type UnsafeClusterServiceServer interface {
	mustEmbedUnimplementedClusterServiceServer()
}

func RegisterClusterServiceServer(s grpc.ServiceRegistrar, srv ClusterServiceServer) {
	s.RegisterService(&ClusterService_ServiceDesc, srv)
}

func _ClusterService_ClusterFunc_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ClusterRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ClusterServiceServer).ClusterFunc(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ClusterService/ClusterFunc",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ClusterServiceServer).ClusterFunc(ctx, req.(*ClusterRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ClusterService_ServiceDesc is the grpc.ServiceDesc for ClusterService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ClusterService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "ClusterService",
	HandlerType: (*ClusterServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ClusterFunc",
			Handler:    _ClusterService_ClusterFunc_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "face.proto",
}
