// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.0
// 	protoc        v3.20.1
// source: face.proto

package pbface

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Textmessage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Textmes string `protobuf:"bytes,1,opt,name=textmes,proto3" json:"textmes,omitempty"`
}

func (x *Textmessage) Reset() {
	*x = Textmessage{}
	if protoimpl.UnsafeEnabled {
		mi := &file_face_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Textmessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Textmessage) ProtoMessage() {}

func (x *Textmessage) ProtoReflect() protoreflect.Message {
	mi := &file_face_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Textmessage.ProtoReflect.Descriptor instead.
func (*Textmessage) Descriptor() ([]byte, []int) {
	return file_face_proto_rawDescGZIP(), []int{0}
}

func (x *Textmessage) GetTextmes() string {
	if x != nil {
		return x.Textmes
	}
	return ""
}

type Bytesmessage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Bytesmes []byte `protobuf:"bytes,1,opt,name=bytesmes,proto3" json:"bytesmes,omitempty"`
}

func (x *Bytesmessage) Reset() {
	*x = Bytesmessage{}
	if protoimpl.UnsafeEnabled {
		mi := &file_face_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Bytesmessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Bytesmessage) ProtoMessage() {}

func (x *Bytesmessage) ProtoReflect() protoreflect.Message {
	mi := &file_face_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Bytesmessage.ProtoReflect.Descriptor instead.
func (*Bytesmessage) Descriptor() ([]byte, []int) {
	return file_face_proto_rawDescGZIP(), []int{1}
}

func (x *Bytesmessage) GetBytesmes() []byte {
	if x != nil {
		return x.Bytesmes
	}
	return nil
}

type FaceRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	FileID   int32  `protobuf:"varint,1,opt,name=fileID,proto3" json:"fileID,omitempty"`
	Format   string `protobuf:"bytes,2,opt,name=format,proto3" json:"format,omitempty"`
	Bytesmes []byte `protobuf:"bytes,3,opt,name=bytesmes,proto3" json:"bytesmes,omitempty"`
}

func (x *FaceRequest) Reset() {
	*x = FaceRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_face_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FaceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FaceRequest) ProtoMessage() {}

func (x *FaceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_face_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FaceRequest.ProtoReflect.Descriptor instead.
func (*FaceRequest) Descriptor() ([]byte, []int) {
	return file_face_proto_rawDescGZIP(), []int{2}
}

func (x *FaceRequest) GetFileID() int32 {
	if x != nil {
		return x.FileID
	}
	return 0
}

func (x *FaceRequest) GetFormat() string {
	if x != nil {
		return x.Format
	}
	return ""
}

func (x *FaceRequest) GetBytesmes() []byte {
	if x != nil {
		return x.Bytesmes
	}
	return nil
}

type Face struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	X1 int32   `protobuf:"varint,1,opt,name=x1,proto3" json:"x1,omitempty"`
	Y1 int32   `protobuf:"varint,2,opt,name=y1,proto3" json:"y1,omitempty"`
	X2 int32   `protobuf:"varint,3,opt,name=x2,proto3" json:"x2,omitempty"`
	Y2 int32   `protobuf:"varint,4,opt,name=y2,proto3" json:"y2,omitempty"`
	V  []int32 `protobuf:"varint,5,rep,packed,name=v,proto3" json:"v,omitempty"`
}

func (x *Face) Reset() {
	*x = Face{}
	if protoimpl.UnsafeEnabled {
		mi := &file_face_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Face) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Face) ProtoMessage() {}

func (x *Face) ProtoReflect() protoreflect.Message {
	mi := &file_face_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Face.ProtoReflect.Descriptor instead.
func (*Face) Descriptor() ([]byte, []int) {
	return file_face_proto_rawDescGZIP(), []int{3}
}

func (x *Face) GetX1() int32 {
	if x != nil {
		return x.X1
	}
	return 0
}

func (x *Face) GetY1() int32 {
	if x != nil {
		return x.Y1
	}
	return 0
}

func (x *Face) GetX2() int32 {
	if x != nil {
		return x.X2
	}
	return 0
}

func (x *Face) GetY2() int32 {
	if x != nil {
		return x.Y2
	}
	return 0
}

func (x *Face) GetV() []int32 {
	if x != nil {
		return x.V
	}
	return nil
}

type FaceResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	FileID  int32   `protobuf:"varint,1,opt,name=fileID,proto3" json:"fileID,omitempty"`
	Faceres []*Face `protobuf:"bytes,2,rep,name=faceres,proto3" json:"faceres,omitempty"`
}

func (x *FaceResponse) Reset() {
	*x = FaceResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_face_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FaceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FaceResponse) ProtoMessage() {}

func (x *FaceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_face_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FaceResponse.ProtoReflect.Descriptor instead.
func (*FaceResponse) Descriptor() ([]byte, []int) {
	return file_face_proto_rawDescGZIP(), []int{4}
}

func (x *FaceResponse) GetFileID() int32 {
	if x != nil {
		return x.FileID
	}
	return 0
}

func (x *FaceResponse) GetFaceres() []*Face {
	if x != nil {
		return x.Faceres
	}
	return nil
}

var File_face_proto protoreflect.FileDescriptor

var file_face_proto_rawDesc = []byte{
	0x0a, 0x0a, 0x66, 0x61, 0x63, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x27, 0x0a, 0x0b,
	0x54, 0x65, 0x78, 0x74, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x74,
	0x65, 0x78, 0x74, 0x6d, 0x65, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x74, 0x65,
	0x78, 0x74, 0x6d, 0x65, 0x73, 0x22, 0x2a, 0x0a, 0x0c, 0x42, 0x79, 0x74, 0x65, 0x73, 0x6d, 0x65,
	0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x62, 0x79, 0x74, 0x65, 0x73, 0x6d, 0x65,
	0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x08, 0x62, 0x79, 0x74, 0x65, 0x73, 0x6d, 0x65,
	0x73, 0x22, 0x59, 0x0a, 0x0b, 0x46, 0x61, 0x63, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x12, 0x16, 0x0a, 0x06, 0x66, 0x69, 0x6c, 0x65, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05,
	0x52, 0x06, 0x66, 0x69, 0x6c, 0x65, 0x49, 0x44, 0x12, 0x16, 0x0a, 0x06, 0x66, 0x6f, 0x72, 0x6d,
	0x61, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x66, 0x6f, 0x72, 0x6d, 0x61, 0x74,
	0x12, 0x1a, 0x0a, 0x08, 0x62, 0x79, 0x74, 0x65, 0x73, 0x6d, 0x65, 0x73, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x0c, 0x52, 0x08, 0x62, 0x79, 0x74, 0x65, 0x73, 0x6d, 0x65, 0x73, 0x22, 0x54, 0x0a, 0x04,
	0x46, 0x61, 0x63, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x78, 0x31, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05,
	0x52, 0x02, 0x78, 0x31, 0x12, 0x0e, 0x0a, 0x02, 0x79, 0x31, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05,
	0x52, 0x02, 0x79, 0x31, 0x12, 0x0e, 0x0a, 0x02, 0x78, 0x32, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05,
	0x52, 0x02, 0x78, 0x32, 0x12, 0x0e, 0x0a, 0x02, 0x79, 0x32, 0x18, 0x04, 0x20, 0x01, 0x28, 0x05,
	0x52, 0x02, 0x79, 0x32, 0x12, 0x0c, 0x0a, 0x01, 0x76, 0x18, 0x05, 0x20, 0x03, 0x28, 0x05, 0x52,
	0x01, 0x76, 0x22, 0x47, 0x0a, 0x0c, 0x46, 0x61, 0x63, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x66, 0x69, 0x6c, 0x65, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x05, 0x52, 0x06, 0x66, 0x69, 0x6c, 0x65, 0x49, 0x44, 0x12, 0x1f, 0x0a, 0x07, 0x66, 0x61,
	0x63, 0x65, 0x72, 0x65, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x05, 0x2e, 0x46, 0x61,
	0x63, 0x65, 0x52, 0x07, 0x66, 0x61, 0x63, 0x65, 0x72, 0x65, 0x73, 0x32, 0x37, 0x0a, 0x0b, 0x54,
	0x65, 0x78, 0x74, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x28, 0x0a, 0x08, 0x54, 0x65,
	0x78, 0x74, 0x46, 0x75, 0x6e, 0x63, 0x12, 0x0c, 0x2e, 0x54, 0x65, 0x78, 0x74, 0x6d, 0x65, 0x73,
	0x73, 0x61, 0x67, 0x65, 0x1a, 0x0c, 0x2e, 0x54, 0x65, 0x78, 0x74, 0x6d, 0x65, 0x73, 0x73, 0x61,
	0x67, 0x65, 0x22, 0x00, 0x32, 0x3b, 0x0a, 0x0c, 0x42, 0x79, 0x74, 0x65, 0x73, 0x53, 0x65, 0x72,
	0x76, 0x69, 0x63, 0x65, 0x12, 0x2b, 0x0a, 0x09, 0x42, 0x79, 0x74, 0x65, 0x73, 0x46, 0x75, 0x6e,
	0x63, 0x12, 0x0d, 0x2e, 0x42, 0x79, 0x74, 0x65, 0x73, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65,
	0x1a, 0x0d, 0x2e, 0x42, 0x79, 0x74, 0x65, 0x73, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x22,
	0x00, 0x32, 0x38, 0x0a, 0x0b, 0x46, 0x61, 0x63, 0x65, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65,
	0x12, 0x29, 0x0a, 0x08, 0x46, 0x61, 0x63, 0x65, 0x46, 0x75, 0x6e, 0x63, 0x12, 0x0c, 0x2e, 0x46,
	0x61, 0x63, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x0d, 0x2e, 0x46, 0x61, 0x63,
	0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x42, 0x0b, 0x5a, 0x09, 0x2e,
	0x2e, 0x2f, 0x70, 0x62, 0x66, 0x61, 0x63, 0x65, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_face_proto_rawDescOnce sync.Once
	file_face_proto_rawDescData = file_face_proto_rawDesc
)

func file_face_proto_rawDescGZIP() []byte {
	file_face_proto_rawDescOnce.Do(func() {
		file_face_proto_rawDescData = protoimpl.X.CompressGZIP(file_face_proto_rawDescData)
	})
	return file_face_proto_rawDescData
}

var file_face_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_face_proto_goTypes = []interface{}{
	(*Textmessage)(nil),  // 0: Textmessage
	(*Bytesmessage)(nil), // 1: Bytesmessage
	(*FaceRequest)(nil),  // 2: FaceRequest
	(*Face)(nil),         // 3: Face
	(*FaceResponse)(nil), // 4: FaceResponse
}
var file_face_proto_depIdxs = []int32{
	3, // 0: FaceResponse.faceres:type_name -> Face
	0, // 1: TextService.TextFunc:input_type -> Textmessage
	1, // 2: BytesService.BytesFunc:input_type -> Bytesmessage
	2, // 3: FaceService.FaceFunc:input_type -> FaceRequest
	0, // 4: TextService.TextFunc:output_type -> Textmessage
	1, // 5: BytesService.BytesFunc:output_type -> Bytesmessage
	4, // 6: FaceService.FaceFunc:output_type -> FaceResponse
	4, // [4:7] is the sub-list for method output_type
	1, // [1:4] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_face_proto_init() }
func file_face_proto_init() {
	if File_face_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_face_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Textmessage); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_face_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Bytesmessage); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_face_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FaceRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_face_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Face); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_face_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FaceResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_face_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   3,
		},
		GoTypes:           file_face_proto_goTypes,
		DependencyIndexes: file_face_proto_depIdxs,
		MessageInfos:      file_face_proto_msgTypes,
	}.Build()
	File_face_proto = out.File
	file_face_proto_rawDesc = nil
	file_face_proto_goTypes = nil
	file_face_proto_depIdxs = nil
}
